//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNA
    {
        public COMUNA()
        {
            this.ADMINISTRADOR = new HashSet<ADMINISTRADOR>();
            this.CLIENTE = new HashSet<CLIENTE>();
            this.PROVEEDOR = new HashSet<PROVEEDOR>();
            this.VENDEDOR = new HashSet<VENDEDOR>();
        }
    
        public decimal ID_COMUNA { get; set; }
        public string NOMBRE_COMUNA { get; set; }
        public decimal ID_REGION { get; set; }
    
        public virtual ICollection<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual ICollection<VENDEDOR> VENDEDOR { get; set; }
    }
}
