//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_VENTA
    {
        public decimal ID_DETALLE_VENTA { get; set; }
        public decimal PRECIO_UNIDAD { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal DESCUENTO { get; set; }
        public string ID_PRODUCTO { get; set; }
        public string ID_VENTA { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual VENTA VENTA { get; set; }
    }
}
