//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ORDEN_PEDIDO
    {
        public DETALLE_ORDEN_PEDIDO()
        {
            this.RECEPCION_PEDIDO = new HashSet<RECEPCION_PEDIDO>();
        }
    
        public decimal ID_DETALLE_ORDEN { get; set; }
        public decimal CANT_POR_PACK { get; set; }
        public decimal PRECIO_COMPRA { get; set; }
        public string ID_PRODUCTO { get; set; }
        public decimal ID_ORDEN_PEDIDO { get; set; }
    
        public virtual ORDEN_PEDIDO ORDEN_PEDIDO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual ICollection<RECEPCION_PEDIDO> RECEPCION_PEDIDO { get; set; }
    }
}
