//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_ORDEN
    {
        public ESTADO_ORDEN()
        {
            this.ORDEN_PEDIDO = new HashSet<ORDEN_PEDIDO>();
        }
    
        public decimal ID_ESTADO_ORDEN { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<ORDEN_PEDIDO> ORDEN_PEDIDO { get; set; }
    }
}
