//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAMILIA_PRODUCTO
    {
        public FAMILIA_PRODUCTO()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal ID_FAMILIA_PRODUCTO { get; set; }
        public string NOMBRE { get; set; }
        public decimal ID_PROVEEDOR { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
