//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORME
    {
        public decimal ID_INFORME { get; set; }
        public System.DateTime FECHA_INFORME { get; set; }
        public string DESCRIPCION { get; set; }
        public string RUT_ADMINISTRADOR { get; set; }
        public decimal ID_TIPO_INFORME { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR { get; set; }
        public virtual TIPO_INFORME TIPO_INFORME { get; set; }
    }
}
