//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_PEDIDO
    {
        public ORDEN_PEDIDO()
        {
            this.DETALLE_ORDEN_PEDIDO = new HashSet<DETALLE_ORDEN_PEDIDO>();
        }
    
        public decimal ID_ORDEN_PEDIDO { get; set; }
        public System.DateTime FECHA_PEDIDO { get; set; }
        public System.DateTime FECHA_ENTREGA { get; set; }
        public decimal VALOR_FINAL_PEDIDO { get; set; }
        public string RUT_ADMINISTRADOR { get; set; }
        public decimal ID_ESTADO_ORDEN { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR { get; set; }
        public virtual ICollection<DETALLE_ORDEN_PEDIDO> DETALLE_ORDEN_PEDIDO { get; set; }
        public virtual ESTADO_ORDEN ESTADO_ORDEN { get; set; }
    }
}
