//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLE_ORDEN_PEDIDO = new HashSet<DETALLE_ORDEN_PEDIDO>();
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
        }
    
        public string ID_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public System.DateTime FECHA_ELABORACION { get; set; }
        public System.DateTime FEC_VENCIMIENTO { get; set; }
        public decimal PRECIO_VENTA { get; set; }
        public decimal STOCK { get; set; }
        public decimal ID_TIPO_PRODUCTO { get; set; }
        public decimal ID_FAMILIA_PRODUCTO { get; set; }
    
        public virtual ICollection<DETALLE_ORDEN_PEDIDO> DETALLE_ORDEN_PEDIDO { get; set; }
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual FAMILIA_PRODUCTO FAMILIA_PRODUCTO { get; set; }
    }
}
