//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.FAMILIA_PRODUCTO = new HashSet<FAMILIA_PRODUCTO>();
        }
    
        public decimal ID_PROVEEDOR { get; set; }
        public string NOMBRE_PROV { get; set; }
        public decimal TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public decimal ID_COMUNA { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<FAMILIA_PRODUCTO> FAMILIA_PRODUCTO { get; set; }
    }
}
