//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCION_PEDIDO
    {
        public decimal ID_RECEPCION { get; set; }
        public System.DateTime FECHA_RECEPCION { get; set; }
        public string COMENTARIO { get; set; }
        public decimal ID_DETALLE_ORDEN { get; set; }
        public string RUT_ADMINISTRADOR { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR { get; set; }
        public virtual DETALLE_ORDEN_PEDIDO DETALLE_ORDEN_PEDIDO { get; set; }
    }
}
