//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_ABONO
    {
        public decimal ID_ABONO { get; set; }
        public decimal MONTO_ABONADO { get; set; }
        public decimal ID_FIADO { get; set; }
    
        public virtual FIADO FIADO { get; set; }
    }
}
