//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_VENTA
    {
        public TIPO_VENTA()
        {
            this.VENTA = new HashSet<VENTA>();
        }
    
        public decimal ID_TIPO_VENTA { get; set; }
        public string NOMBRE_TIPO { get; set; }
    
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
