//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_INFORME
    {
        public TIPO_INFORME()
        {
            this.INFORME = new HashSet<INFORME>();
        }
    
        public decimal ID_TIPO_INFORME { get; set; }
        public string NOMBRE_TIPO { get; set; }
    
        public virtual ICollection<INFORME> INFORME { get; set; }
    }
}
