//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.ADMINISTRADOR = new HashSet<ADMINISTRADOR>();
            this.VENDEDOR = new HashSet<VENDEDOR>();
        }
    
        public string NOMBRE_USUARIO { get; set; }
        public string CONTRASENIA { get; set; }
    
        public virtual ICollection<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual ICollection<VENDEDOR> VENDEDOR { get; set; }
    }
}
