//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public VENTA()
        {
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
            this.FIADO = new HashSet<FIADO>();
        }
    
        public string ID_VENTA { get; set; }
        public decimal VALOR_TOTAL { get; set; }
        public decimal DESCUENTO_TOTAL { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string RUT_VENDEDOR { get; set; }
        public System.DateTime FECHA_VENTA { get; set; }
        public decimal ID_TIPO_VENTA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual ICollection<FIADO> FIADO { get; set; }
        public virtual TIPO_VENTA TIPO_VENTA { get; set; }
        public virtual VENDEDOR VENDEDOR { get; set; }
    }
}
