//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YuyitosBDEntities : DbContext
    {
        public YuyitosBDEntities()
            : base("name=YuyitosBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<DETALLE_ORDEN_PEDIDO> DETALLE_ORDEN_PEDIDO { get; set; }
        public DbSet<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public DbSet<ESTADO_FIADO> ESTADO_FIADO { get; set; }
        public DbSet<ESTADO_ORDEN> ESTADO_ORDEN { get; set; }
        public DbSet<FAMILIA_PRODUCTO> FAMILIA_PRODUCTO { get; set; }
        public DbSet<FIADO> FIADO { get; set; }
        public DbSet<INFORME> INFORME { get; set; }
        public DbSet<ORDEN_PEDIDO> ORDEN_PEDIDO { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RECEPCION_PEDIDO> RECEPCION_PEDIDO { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<REGISTRO_ABONO> REGISTRO_ABONO { get; set; }
        public DbSet<TIPO_INFORME> TIPO_INFORME { get; set; }
        public DbSet<TIPO_VENTA> TIPO_VENTA { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VENDEDOR> VENDEDOR { get; set; }
        public DbSet<VENTA> VENTA { get; set; }
    }
}
